"use strict";
var aglsl = require("./lib/aglsl");
exports.aglsl = aglsl;
var attributes = require("./lib/attributes");
exports.attributes = attributes;
var base = require("./lib/base");
exports.base = base;
var events = require("./lib/events");
exports.events = events;
var image = require("./lib/image");
exports.image = image;
var library = require("./lib/library");
exports.library = library;
var managers = require("./lib/managers");
exports.managers = managers;
var AttributesBuffer_1 = require("@awayjs/core/lib/attributes/AttributesBuffer");
var BitmapImage2D_1 = require("@awayjs/core/lib/image/BitmapImage2D");
var BitmapImageCube_1 = require("@awayjs/core/lib/image/BitmapImageCube");
var Image2D_1 = require("@awayjs/core/lib/image/Image2D");
var ImageCube_1 = require("@awayjs/core/lib/image/ImageCube");
var SpecularImage2D_1 = require("@awayjs/core/lib/image/SpecularImage2D");
var Sampler2D_1 = require("@awayjs/core/lib/image/Sampler2D");
var SamplerCube_1 = require("@awayjs/core/lib/image/SamplerCube");
base.Stage.registerAbstraction(attributes.GL_AttributesBuffer, AttributesBuffer_1.AttributesBuffer);
base.Stage.registerAbstraction(image.GL_RenderImage2D, Image2D_1.Image2D);
base.Stage.registerAbstraction(image.GL_RenderImageCube, ImageCube_1.ImageCube);
base.Stage.registerAbstraction(image.GL_BitmapImage2D, BitmapImage2D_1.BitmapImage2D);
base.Stage.registerAbstraction(image.GL_BitmapImageCube, BitmapImageCube_1.BitmapImageCube);
base.Stage.registerAbstraction(image.GL_BitmapImage2D, SpecularImage2D_1.SpecularImage2D);
base.Stage.registerAbstraction(image.GL_Sampler2D, Sampler2D_1.Sampler2D);
base.Stage.registerAbstraction(image.GL_SamplerCube, SamplerCube_1.SamplerCube);
