export enum ContextGLBlendFactor
{
	DESTINATION_ALPHA,
	DESTINATION_COLOR,
	ONE,
	ONE_MINUS_DESTINATION_ALPHA,
	ONE_MINUS_DESTINATION_COLOR,
	ONE_MINUS_SOURCE_ALPHA,
	ONE_MINUS_SOURCE_COLOR,
	SOURCE_ALPHA,
	SOURCE_COLOR,
	ZERO
}